package org.bitfennec.lime.keyboard

val doubleFlyMnemonicPreset: Map<Int, String> = hashMapOf(
    45 to "iu",
    51 to "ei",
    46 to "uan van",
    48 to "ue ve",
    53 to "un vn",
    49 to "sh",
    37 to "ch",
    43 to "uo",
    44 to "ie",
    47 to "iong ong",
    32 to "ai",
    34 to "en",
    35 to "eng",
    36 to "ang",
    38 to "an",
    39 to "ing uai",
    40 to "iang uang",
    75 to "分词",
    54 to "ou",
    52 to "ia ua",
    31 to "ao",
    50 to "ui zh",
    30 to "in",
    42 to "iao",
    41 to "ian",
)